[lint]
select = [
    "D", # pydocstyle
    "E", # pycodestyle
    "F", # Pyflakes
    "I", # isort
]

[lint.pydocstyle]
convention = "numpy"

# See https://docs.astral.sh/ruff/linter/#rule-selection
