target:
    nS: 19  # number of target slices
    material: "tungsten"
    xy: 25.  # [cm] full length in x and y
    HeT: 90  # He temperature in Celsius degrees, integer, Medium with name PressurisedHe<value> must exist in media.geo file

    L:  # slice lengths [cm]
        - 4.5
        - 1.8
        - 1.7
        - 1.7
        - 1.8
        - 1.9
        - 2.1
        - 1.9
        - 2.1
        - 2.4
        - 2.8
        - 3.3
        - 4.1
        - 5.6
        - 8.8
        - 17.2
        - 28.7
        - 28.8
        - 28.8

    G:  # gaps after each slice [cm]
        - 0.45
        - 0.45
        - 0.45
        - 0.45
        - 0.45
        - 0.45
        - 0.45
        - 0.45
        - 0.45
        - 0.45
        - 0.45
        - 0.45
        - 0.45
        - 0.45
        - 0.48
        - 0.5
        - 0.68
        - 0.68
        - 0
