Geant4_UserGeometry:     "geomRoot"
Geant4_PhysicsList:      "emStandard"
Geant4_SpecialProcess:   ""
Geant4_SpecialStacking:  false
Geant4_Multithreaded:    false

#Geant4_MaxNStep:         10000    #default is 30000
Geant4_Commands:
 - /mcVerbose/all 0
 - /mcTracking/loopVerbose 0
 - /mcPhysics/g4HadronicProcessStoreVerbose 0
 - /process/em/verbose 0
 - /process/eLoss/verbose 0
 - /mcDet/setIsLocalMagField true

MonteCarlo_Process:
    PAIR:         1        #pair production
    COMP:         1        #Compton scattering
    PHOT:         1        #photo electric effect
    PFIS:         0        #photofission
    DRAY:         1        #delta-ray
    ANNI:         1        #annihilation
    BREM:         1        #bremsstrahlung
    HADR:         1        #hadronic process
    MUNU:         1        #muon nuclear interaction
    DCAY:         1        #decay
    LOSS:         1        #energy loss
    MULS:         1        #multiple scattering

MonteCarlo_Cut:
    CUTGAM:       1.0E-3   #gammas (GeV)
    CUTELE:       1.0E-3   #electrons (GeV)
    CUTNEU:       1.0E-3   #neutral hadrons (GeV)
    CUTHAD:       1.0E-3   #charged hadrons (GeV)
    CUTMUO:       1.0E-3   #muons (GeV)
    BCUTE:        1.0E-3   #electron bremsstrahlung (GeV)
    BCUTM:        1.0E-3   #muon and hadron bremsstrahlung (GeV)
    DCUTE:        1.0E-3   #electron delta-rays (GeV)
    DCUTM:        1.0E-3   #muon and hadron delta-rays (GeV)
    PPCUTM:       1.0E-3   #direct pair production by muons (GeV)
    TOFMAX:       1.E10    #time of flight cut (s)
